apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: verify-enterprise-contract-task
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: verify-enterprise-contract-task
    app.kubernetes.io/part-of: ec-release-debugging
  name: verify-enterprise-contract-task
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: verify-enterprise-contract-task
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: verify-enterprise-contract-task
    spec:
      containers:
      - image: quay.io/jstuart/verify-enterprise-contract-task@sha256:1ae2467bd286392c8f226d8dcde3d93a4bff25b70efb8f0e16f286719ec197a5
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
